// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnshgjpiewvhlnqfzqqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuc2hnanBpZXd2aGxucWZ6cXFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MjM4MDYsImV4cCI6MjA2Nzk5OTgwNn0.4WI9WZ7dm1i15yacWB3zzon0W_zbDA0X8mB2p4rh3Zc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});